### ISSUE TITLE
Winetricks does not always create wintricks.log causing re-installs to happen

### ISSUE THREAD

**Issue by MrCraigen** [simons-public/protonfixes#11]
**Is your feature request related to a problem? Please describe.**
I can see in the logs that every time you run a game with protonfixes script that has a winetricks command it in. That it will always run the winetricks command, before the game starts. Which makes the start up much slower then it should be.

**Describe the solution you'd like**
Have a check whenever a winetricks is installed or not before it runs the command.

**Describe alternatives you've considered**
Not 100% sure how, maybe there is a check in winetricks.

**Comment by simons-public** [comment]
There [is a check to see if winetricks was already run](https://github.com/simons-public/protonfixes/blob/1.0.10/protonfixes/util.py#L81-L104) in place, but it might not be working on your setup for some reason. 
Is there a `winetricks.log` file in the prefix of the game that it keeps running on? If the winetricks log isn't getting created it will keep trying to install.

**Comment by MrCraigen** [comment]
@simons-public You are correct, for some reason the winetricks.log aren't created from my scripts in localfixes folder.

**Comment by simons-public** [comment]
I'll see if I can replicate it on my end and try to find a fix. Can you post a log as well?

**Comment by MrCraigen** [comment]
Sorry for the late reply, here is the log from my current fixscript that im working on.

https://gist.github.com/MrCraigen/67556f2094b3ea78c717b79f0d8ed301

Here is the script
https://gist.github.com/MrCraigen/b0c20209f59f13494c3c9e859350d9be

**Comment by simons-public** [comment]
Can you check if there is a `winetricks.log` file in the `GAMEID/pfx` folder for the game? And if there is one, can you post the contents? It might be `checkinstalled` function isn't reading it properly.

**Comment by MrCraigen** [comment]
I tried to find it, but i can't seem to find it. Is there a way to generate it?

**Comment by simons-public** [comment]
I reworked the protontricks utility to use the Proton wine instead of system wine. I'm hoping that might have fixed the issue. I just pushed a new version to pypi, can you update and see if you're still having the issue?

**Comment by pchome** [comment]
I can reproduce this bug using `util.protontricks('vd=1920x1080')`, this should simply create and apply a temporary `vd.reg` file (for setting wine virtual desktop resolution). See `$ winetricks settings list` for details.

Moreover, I can see a several records for `settings` in my old `winetricks.log` files, e.g.
```
csmt=off
csmt=on
```
so, even if this bug will be fixed, there is another obvious problem -- such changes will stop work after several attempts.

Maybe better to create and use own log file to track all applied fixes, e.g. `protonfixes.log` or `protontricks.log`. And also handle possible `settings` problem : e.g. `vd=...` can be changed several times, switching from 1080 to 720 and wise-versa,  so protonfixes may require more advanced tracking system to detect this behaviour (simple check/change second part if `=` detected).

**Comment by pchome** [comment]
@pchome 
> Maybe better to create and use own log file to track all applied fixes

Or an INI file, `protontricks.ini`.

**Comment by simons-public** [comment]
@pchome Thanks, I realized that util.checkinstalled was checking the winetricks log from top to bottom, when it logs in chronological order. I updated it so it checks from the bottom first, which should fix the issue when multiple winetricks with the same name are logged.

**Comment by pchome** [comment]
Unfortunately `winetricks.log` don't created for `vd=...` verbs, but `csmt=on` and `csmt=off` are ok.
