### ISSUE TITLE
kdialog splash not working

### ISSUE THREAD

**Issue by soredake** [simons-public/protonfixes#121]
**Describe the bug**
Kdialog splash is not working, and no fixes installed. If i install `python-cef python-kivy` kdialog is working and fixes installed.

**To Reproduce**
Install arch, install kdialog, try launch game with fixes.

**Expected behavior**
Kdialog wokring.

**Logs**
[kdialog.log](https://github.com/simons-public/protonfixes/files/4393672/kdialog.log)

```
from protonfixes import debug
import protonfixes
```

**Operating System:**
 - Distro and Version: ArchLinux
 - Proton Version: Protonfixes 5.0-5

**Game (if applicable):**
 - Game Name: Collapse
 - Game ID: 289620

**Additional Information**
Add any other information [i.e. Modified Proton, Non-default Steam Library folder, etc] that might be useful in troubleshooting.

**Comment by mrjackv** [comment]
Looked at the log, I made a mistake :scream: 
`App` is a kivy class, but it might not exist and so pf crashes
Will send PR asap
