### ISSUE TITLE
Smite Gamefix

### ISSUE THREAD

**Issue by Serph91P** [simons-public/protonfixes#129]
Hi can you please add Smite gamefixes?
I cannot code so Iam asking.

You would need to add:
- protontricks 386360 dotnet40 physx vcrun2010 vcrun2012 vcrun2013 vcrun2015
- protontricks 386360 winecfg change Windows version to Windows XP
-Add these as (native, buildin): dxgi d3d9 d3d10 d3d10core d3d11 d3dx9_43 d3dx10_43 d3dx11_43
- set Launch options to "PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 %command%" 

About the EAC I dont know if this is possible to also add you need the files from paladins.

(From the Paladins/Binaries/EasyAntiCheat/ folder copy everything except for the Certificates and Launcher folder to the Steam/steamapps/common/SMITE/Binaries/EasyAntiCheat/ folder copy both EasyAntiCheat dll files in the EasyAntiCheat folder to Steam/steamapps/common/SMITE/Binaries/Win32/EasyAntiCheat/and Steam/steamapps/common/SMITE/Binaries/Win64/EasyAntiCheat/)

Thank You

**Comment by simons-public** [comment]
@Serph91P Is there another location the EAC files can be legally acquired from? I'm hesitant to add a fix that requires files from another game if it might not be owned/installed.

**Comment by Serph91P** [comment]
@simons-puplic the Problem is Smite hast its own EAC Files. Nur those lac Sole fixes witch the ones from Paladine have. So I guess it is not possible to add.
