### ISSUE TITLE
autoimport (most) of your gamefixes into my stl

### ISSUE THREAD

**Issue by frostworx** [simons-public/protonfixes#137]
Hi,
I'm the author of the Steam wrapper tool[ SteamTinkerLaunch (or short stl)](https://github.com/frostworx/steamtinkerlaunch)
which is started directly as Steam startoption `stl %command%` and offers a wide range of extra features for the launched game.
One of them is that required configurations get auto applied to get a game working ootb.
Currently I'm planning to implement "autotweaks" - a function to (optionally) search for required tweaks on different platforms
and think it would be great to implement an "importer" for your gamefixes as well.
Basically stl would clone/pull protonfixes and when a game is launched it would check if a matching "$SteamAppId.py" file exists and would extract the tweaks from there (at least winetricks packages, exe overrides, commandline parameters, registry entries, env variables, maybe later also custom scripts)
I opened an issue for myself, to gather some ideas already [here](https://github.com/frostworx/steamtinkerlaunch/issues/40)

Would be great if this is ok for you, else I would just write a quick offline script which parses your gamefixes once and creates static stl "tweak files" for bundling with my project (which I guess should not be a problem, right?)
cheers!

**Comment by simons-public** [comment]
@frostworx Sorry for the late response, importing the gamefixes is perfectly fine with me.

SteamTinkerLaunch looks pretty cool, I'll definitely have to check that out when I have some time!

**Comment by frostworx** [comment]
Hello @simons-public!
Thank you very much for the reply, for the permission to pull your gamefixes and of course for the friendly words!
I already have a working implementation finished, but it is not committed yet.
_(I opened an issue for me [here](https://github.com/frostworx/steamtinkerlaunch/issues/46) just yesterday)_
The next push will be pretty big :)

**Comment by frostworx** [comment]
Hi again, just released v1.6.0 with initial protonfixes support :)
https://github.com/frostworx/steamtinkerlaunch/releases/tag/v1.6.0
I think I can close this issue here :)
Thanks a lot again!
