### ISSUE TITLE
Dragon ball FighterZ help

### ISSUE THREAD

**Issue by tuxtergames** [simons-public/protonfixes#152]
Theres a script in valve wiki that make steam avoid launch EAC making the game launch offline, work for a few time but theres a few time don't.

We have an solution in valve wiki for dragon ball fighterz with protonfix that not working anymore

**Describe the solution you'd like**
The script should run 'DBFighterZ.exe' instead 'RED/Binaries/Win64/RED-Win64-Shipping.exe', even if I create a script inside protonfix folder, stean refuse to see it.

**Describe alternatives you've considered**
maybe give some help to make it work

**Additional context**
reference of this issue

https://github.com/ValveSoftware/Proton/issues/1240#issuecomment-626401185

here a print of folder and terminal output of steam, tks for anyhelp!
![image](https://user-images.githubusercontent.com/26095484/114786379-61e2cf80-9d54-11eb-9b26-59f6d963cb5c.png)
[steam-678950.log](https://github.com/simons-public/protonfixes/files/6313955/steam-678950.log)

**Comment by rezzafr33** [comment]
move `678950.py` one folder up, It should be under `~/.config/protonfixes/localfixes/`, instead yours is on `~/.config/protonfixes/localfixes/localfixes/`

**Comment by tuxtergames** [comment]
> move `678950.py` one folder up, It should be under `~/.config/protonfixes/localfixes/`, instead yours is on `~/.config/protonfixes/localfixes/localfixes/`

made a big mass here, still don't work, 

>>> Adding process 49142 for game ID 678950
ProtonFixes[49160] INFO: Running protonfixes
ProtonFixes[49160] INFO: Running checks
ProtonFixes[49160] INFO: All checks successful
ProtonFixes[49160] INFO: Using global defaults for "DRAGON BALL FighterZ" (678950)
ProtonFixes[49160] INFO: Using local protonfix for "DRAGON BALL FighterZ" (678950)
ProtonFixes[49160] INFO: Changing DBFighterZ.exe to RED/Binaries/Win64/RED-Win64-Shipping.exe
ProtonFixes[49160] INFO: Adding argument -eac-nop-loaded
ProtonFixes[49160] INFO: Checking if winetricks hidewineexports=enable is installed
ProtonFixes[49160] INFO: Getting ms corefonts
>>> Adding process 49157 for game ID 678950
>>> Adding process 49159 for game ID 678950
>>> Adding process 49160 for game ID 678950
^LProtonFixes[49160] INFO: Creating MS Core font links in /media/unidade-3/Steam Games/steamapps/compatdata/678950/pfx/drive_c/windows/Fonts

**Comment by rezzafr33** [comment]
I think as far as protonfixes concern, this issue is solved and should be closed. Lets get back to proton github.
