### ISSUE TITLE
No module named 'protonfixes'

### ISSUE THREAD

**Issue by Zyneris** [simons-public/protonfixes#154]
**Describe the bug**
When attempting to run a game fix, Proton outputs the following:
```
Proton: ************************************************
Proton: THERE IS AN ERROR IN YOUR user_settings.py FILE:
Proton: No module named 'protonfixes'
Proton: ************************************************
```

**To Reproduce**
Installed protonfixes via pip
`pip3 install --user protonfixes`
Added `import protonfixes` to my `user_settings.py`
Launch game via Steam

**Expected behavior**
Proton finding the module and starting the process of running the game fix.

**Logs**
[Log](https://gist.github.com/Zyneris/4d536fc642ae56a55b7330598c7215b8)
[user_settings.py](https://gist.github.com/Zyneris/0ca1b5f8adf7d9c20ea0a74f52b51192)

**Operating System:**
 - Distro and Version: Arch Linux 5.11.12-arch1-1
 - Proton Version: Proton 6.3-2

**Game (if applicable):**
 - Game Name:
 - Game ID:

**Additional Information**
If I place protonfixes/ inside of Proton 6.3/ the module is seen by Proton. However this then causes an error where it cannot find winetricks despite winetricks being located in my $PATH.

**Comment by simons-public** [comment]
It's possible that proton is not checking your user modules. Have you tried installing it globally as described in the readme?

protonfixes looks for `winetricks` in $PATH, but it could be that the $PATH for the proton process doesn't match yours. You can check the $PATH variable for the process in `/proc/$PID/environ` to see if it's set correctly.

**Comment by Zyneris** [comment]
Sorry for the late reply, I no longer have this setup to test any changes. Closing ticket as such.
