### ISSUE TITLE
Implement game config file edit

### ISSUE THREAD

**Issue by pchome** [simons-public/protonfixes#21]
Probably useful feature. `util.set_game_option('section', 'option', 'value', 'file')`?

**Describe the solution you'd like**
Similarly to `util.set_dxvk_option()` we can use `/path/to/pfx/drive_c/users/steamuser/My Documents/GameName/config.file` to modify game's INI configuration file.

**Additional context**
Not sure if there is any game requires modification of game's config to be launched, but it could be useful for local gamefixes to take more control in one place.

Also we know more about system, so some system specific options could be modified.
E.g. common Unreal Engine fixes, like `PoolSize` (https://pcgamingwiki.com/wiki/Engine:Unreal_Engine_3#Stuttering_and_texture_.22popping.22)

I'll probably implement this by myself one day, but if anyone like/want this now -- here is the idea.

**Comment by dreamer** [comment]
I did something similar in fix for Tomb Raider already: https://github.com/simons-public/protonfixes/commit/5fb0e4e56a4b6d583afd6ad7161e969c087d1e55

DOSBox configuration files are really just .ini files and Python's `configparser` module is quite flexible :).

**Comment by pchome** [comment]
Yep, `util.set_dxvk_option()` was created on the base of yours `util.screate_dosbox_conf()` (inspired).

Thanks for idea/example. This issue meant to combine both of them into one generic INI configurator.

_Also I want to state again: I'm bad in python (and English, yes). If there is examples -- I can try to do it ;)_
