### ISSUE TITLE
A Hat in Time and Rise of Nations are missing fixes

### ISSUE THREAD

**Issue by ryao** [simons-public/protonfixes#24]
For Rise of Nations:

https://github.com/ValveSoftware/Proton/issues/298#issuecomment-423711864

The crypt32 workaround is no longer needed as of 3.16-3. However, you need to set sound=alsa (when using PulseAudio), install directmusic and set overrides for dmime, dmsynth, dmusic, dsound, dswave and l3codecx in addition to bypassing the launcher to get it to work.

For A Hat In Time:

https://github.com/ValveSoftware/Proton/issues/173

You need to install xact. There is some minor graphical corruption in act 3 of the first chapter, but aside from that, it seems to work fine.

**Comment by simons-public** [comment]
Added fixes for both, please let me know if they work and I'll close the issue

**Comment by ryao** [comment]
I wiped out my compatdata folders for those two and tried launching them. The first run of each segfaulted, but the second run worked. I don't know why the first run segfaults for each of them. It might be specific to my system.

**Comment by ryao** [comment]
I just retried wiping the compatdata for A Hat in Time and running it again. I get:

```
Traceback (most recent call last):
  File "/home/richard/.local/share/Steam/steamapps/common/Proton 3.16/proton", line 325, in <module>
    win_vr_config = subprocess.check_output([wine_path, "winepath", "-w", vr_config], env=env, stderr=lfile).decode("utf-8")
  File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/richard/.local/share/Steam/steamapps/common/Proton 3.16/dist/bin//wine', 'winepath', '-w', '/home/richard/.local/share/Steam/config']' returned non-zero exit status 1.
>>> Adding process 8873 for game ID 253230
pid 8640 != 8639, skipping destruction (fork without exec?)
Game removed: AppID 253230 "", ProcID 6277 
No cached sticky mapping in ActivateActionSet.
```

I am not sure what the reason is that wine is quitting on first run, but I don't think it needs to be handled in this issue. I'll close it and open a new one when I have time to troubleshoot.

**Comment by ryao** [comment]
I did not notice it at first, but the audio issue in A Hat in Time was not fixed on the fresh install. An override for xaudio2_7 is needed because winetricks doesn't seem to have done it when xact2 was run. :/

**Comment by simons-public** [comment]
Ok, I'll add in the xaudio2_7 override and push up a commit right now

**Comment by ryao** [comment]
@simons-public That fixed it.
