### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by liberodark** [simons-public/protonfixes#25]
Im on manjaro x64 but is not work ?

Have copy and rename user_settings.sample.py to user_settings.py in folder : 
/home/pc/.steam/steam/steamapps/common/Proton 3.16/

Have install sudo pip install cefpython3 & sudo pip install protonfixes
And have add import protonfixes on user_settings.py & user_settings.sample.py

For what not  work is not ok ?

Best Regards

**Comment by dreamer** [comment]
Are you sure you are starting game using Proton 3.16? Can you post steam log?

What happens when you start python3 and type "import protonfixes"?

**Comment by simons-public** [comment]
@liberodark Also, can you post the output of `/tmp/dumps/$USER_stdout.txt`?

If protonfixes is installed you probably won't see any indications unless it is taking a long time to install something

Also, if there are specific games that it is not working for please post that information as well

**Comment by liberodark** [comment]
no is fixed thanks but not work great for most games.
Thanks for your great work
