### ISSUE TITLE
[379720] Doom 2016 ChromaSDK 

### ISSUE THREAD

**Issue by Riesi** [simons-public/protonfixes#26]
Hello I just want to mention that Doom 2016 normally needs more than `vcrun2015` to run without a problem. As far as I can tell your project does not support downloading and replacing things, so that needs to be tackled, if you want to support this kind of fix. 

Here is the Lutris installer script and my Proton issue about it:
[Lutris script](https://lutris.net/games/install/5920/view)
[Proton issue](https://github.com/ValveSoftware/Proton/issues/896)

I don't really mind, if you dislike the idea of downloading things and just close the issue.
Kind regards,
Riesi

**Comment by simons-public** [comment]
I like the idea, I'll see what I can do to get it implemented

**Comment by simons-public** [comment]
Ok, I got it working and was able to get `CChromaEditorLibrary.dll` extracted into the game directory for another game, but I can't run Doom 2016 on the machine I'm testing on. Would you mind testing to see if it works for you?
