### ISSUE TITLE
You can fixe Reckoning ?

### ISSUE THREAD

**Issue by liberodark** [simons-public/protonfixes#29]
Hi,

Just little question for try to fix full screen of reckoning !

Cordialy

https://github.com/ValveSoftware/Proton/issues/783

**Comment by liberodark** [comment]
have this game for try

**Comment by liberodark** [comment]
have 890 games if you want test

**Comment by simons-public** [comment]
I didn't find anything anything in the [Proton Issue](https://github.com/ValveSoftware/Proton/issues/783), the [appdb](https://appdb.winehq.org/objectManager.php?sClass=version&iId=25354), or the [lutris script](https://lutris.net/games/install/6655/view) that deals with fixing the fullscreen resolution. It's likely that it has something to do with the way Proton handles resolution changes (scaling vs outputting to native resolution). I'm closing this for now, but if you figure out a fix that can be implemented please feel free to re-open the issue.
