### ISSUE TITLE
Rise of Nations needs SkipIntroMovies=1 in rise2.ini

### ISSUE THREAD

**Issue by ryao** [simons-public/protonfixes#37]
When installing Rise of Nations: Extended Edition on my cousin's new Linux installation via Steam Family Sharing, I noticed that Rise of Nations has some introduction movies that are not playing, which causes a long pause at start with a black screen.

Rather than fix the introduction movies, it is possible to disable them entirely by putting SkipIntroMovies=1 ~/.local/share/Steam/steamapps/compatdata/287450/pfx/drive_c/users/steamuser/Application Data/Microsoft Games/Rise of Nations/rise2.ini. That file won't exist until first run, but in theory, the game should add any missing entries during first run, so it should be okay to create with just SkipIntroMovies=1 in it. This of course needs testing.

I don't have time to test out ideas to fix the protontricks script until the weekend, but I wanted to report this sooner rather than later.

**Comment by simons-public** [comment]
I think it would be better to figure out which codecs are required for the video and install those, can you test installing some of the available codecs with something like protontricks and see if any work? These are some of the codecs you can install with winetricks/protontricks:
```
allcodecs                All codecs (dirac, ffdshow, icodecs, cinepak, l3codecx, xvid) except wmp (various, 1995-2009)
cinepak                  Cinepak Codec (Radius, 1995)
ffdshow                  ffdshow video codecs (doom9 folks, 2010)
icodecs                  Indeo codecs (Intel, 1998)
l3codecx                 MPEG Layer-3 Audio Codec for Microsoft DirectShow (Microsoft, 2010)
ogg                      OpenCodecs 0.85: FLAC, Speex, Theora, Vorbis, WebM (Xiph.Org Foundation, 2011)
windowscodecs            MS Windows Imaging Component (Microsoft, 2006)
xvid                     Xvid Video Codec (xvid.org, 2009)
wmp10                    Windows Media Player 10 (Microsoft, 2006)
wmp9                     Windows Media Player 9 (Microsoft, 2003) (requires win32 prefix)
```
