### ISSUE TITLE
Age of Empires III is broken

### ISSUE THREAD

**Issue by ryao** [simons-public/protonfixes#38]
When helping out my cousin setup Age of Empires III on his new Linux installation, I discovered that the protontricks compatibility fix for it are broken. Steam did not like the 32-bit prefix and the 32-bit prefix itself is entirely unnecessary, as I had installed it in a 64-bit prefix using proton tricks:

https://github.com/ValveSoftware/Proton/issues/17#issuecomment-423592026

I don't have time to test out ideas to fix the protontricks script until the weekend, but I wanted to report this sooner rather than later.

To be clear, he was using Proton 3.7-8.

**Comment by simons-public** [comment]
A win64 prefix won't work with dotnet 2.0, but if it's not needed (as mentioned in the issue linked) we can get rid of the win32 prefix. I am concerned about the win32 prefix not working though, can you post a debug log?
