### ISSUE TITLE
Activate game fix from runner options

### ISSUE THREAD

**Issue by barni2000** [simons-public/protonfixes#46]
**Describe the solution you'd like**
An environment variable in runner option, for enable fixes by game.
For example: PROTONFIXES_ENABLE=1 %command%

**Describe alternatives you've considered**
May be an wrapper script or PROTONFIXES_DISABLE=1 environment variable.

**Comment by simons-public** [comment]
Ok, protonfixes can be disabled with `PROTONFIXES_DISABLE=1 %command%` now. I don't want users to have to manually enable it individually for each game, but I can see the utility of disabling a fix if you don't want to run it.

**Comment by barni2000** [comment]
Thanks. :smile:
