### ISSUE TITLE
ModuleNotFoundError: No module named 'protonfixes'

### ISSUE THREAD

**Issue by MrCraigen** [simons-public/protonfixes#5]
Not sure if this is the right way to do report this kind of fault. But i need some help, im not an expert when it comes the Python language.

But i follow your small guide, i used the pip installation and installed the stuff i needed to finish it.

I added the line "import protonfixes" in user_settings.py (after #!/usr/bin/env python)

But when i try to launch the game Final Fantasy IX nothing happens, but when i check the error.log in .steam folder. I see the following line:

ModuleNotFoundError: No module named 'protonfixes'

Im missing something?

EDIT: Just side information, my steamapps folder is not under ~/.steam, but in a total diffrent folder and harddriver.

EDIT 2: Im using Linux Mint 19

**Comment by simons-public** [comment]
If it's throwing a ModuleNotFoundError that means the version of python that Proton is using doesn't know where to find module that pip installed. It might mean that proton is using python3 and your system default is python2 or vice-versa. 
 
Can you add this to your user_settings.py and post the output:
```
import sys
print('----------------')
print(sys.executable)
print(sys.modules)
print('----------------')
```

Also, if the path it outputs is something `/usr/bin/python` without the version, run the command `file` with that path and it should show what it's symlinked to.

Also, as a side note, you don't need a #! line in your user_settings.py file, as it is not directly executed but [imported by proton](https://github.com/ValveSoftware/Proton/blob/proton_3.7/proton.in#L142)

**Comment by MrCraigen** [comment]
Thank you for your reply, here is some logs:

ser_settings.py output:
https://gist.github.com/MrCraigen/8d501df26aba85f03ccba88dd4f39714

file /usr/bin/python gave me the output 
"/usr/bin/python: symbolic link to python2.7"

user_settings.py file as of now
https://gist.github.com/MrCraigen/8a99533c87c5ef661e002aaee2bb959b

**Comment by simons-public** [comment]
Ok, so it looks like Proton is running on python3 but your system default is python2, so try running `pip3 install protonfixes` or `python3 -m pip install protonfixes`.

**Comment by MrCraigen** [comment]
That seems to fix the problem with the 

"ModuleNotFoundError: No module named 'protonfixes'" error

But when i try again starting up Final Fantasy IX, nothing happens. I even tried to reinstall the game, nothing.

Any more logs i can provide for you? 
Thank you again for the help!

**Comment by NoXPhasma** [comment]
Run `tail -f /tmp/dumps/${USER}_stdout.txt` on a terminal and start the game. That will show you the Steam stdout and you can see Python errors.

**Comment by simons-public** [comment]
@MrCraigen Yes, please post the /tmp/dumps stdout file, hopefully that will shed some light on the reason it's failing to launch. Also, if you could add this to your `user_settings.py` file it should have some more info:

```
import os
os.environ['DEBUG'] = '1'
```

**Comment by MrCraigen** [comment]
@simons-public Thank you for taking time to resolve my issue. I took out a dump file from when i tried to start up Final Fantasy IX

https://gist.github.com/MrCraigen/d928b9fd6ae3ee427a3021fd641254fe

**Comment by simons-public** [comment]
@MrCraigen It looks like from the debug log that changing the proton arguments isn't working, (i.e. switching FF9_Loader.exe to x64/FF9.exe).

Can you try using this user_settings.py and post the output again:
https://gist.github.com/simons-public/28e9f0f968a3eae32032bb2ea9720cf0

**Comment by MrCraigen** [comment]
I added your settings and I did some more testing, i remember that i have another game that you have provided a fix for aswell. Styx

**Styx**
Old debugging
https://gist.github.com/MrCraigen/e92b9f6829570a69b56d130702d6a88f

New debugging
https://gist.github.com/MrCraigen/85ab3423862212320614bcb1aefc3fbf

**Final Fantasy IX**
New debugging
https://gist.github.com/MrCraigen/43e603234c91abf1594eb7542bd10529

**Comment by simons-public** [comment]
@MrCraigen Sorry, I gave you a bad user_settings.py. I updated the gist, can you try again?
https://gist.github.com/simons-public/28e9f0f968a3eae32032bb2ea9720cf0

**Comment by MrCraigen** [comment]
Ah maybe i did copying it wrong.  Here is the another logs

FF IX
https://gist.github.com/MrCraigen/0d7cc96d7951dbb6cd578437fadc7f1c

Styx
https://gist.github.com/MrCraigen/f93e1922ca3caba126c279c08c74236c

**Comment by simons-public** [comment]
Ok, pretty sure I found the issue. I committed the update to the repo, but I won't be able to upload it to pypi for pip install until I get home.

**Comment by MrCraigen** [comment]
Glad to hear that, let me know after you have uploaded to the pypi. So i can do more testing :)

**Comment by simons-public** [comment]
@MrCraigen Ok, it's uploaded, hopefully it should work now

**Comment by MrCraigen** [comment]
@simons-public Yes! Both Styx and Final Fantasy IX works now without any issue

**Comment by simons-public** [comment]
Awesome! Glad I could help, and thanks for reporting the issue.
