### ISSUE TITLE
Batman™: Arkham Knight raises UnicodeDecodeError on start

### ISSUE THREAD

**Issue by NoXPhasma** [simons-public/protonfixes#53]
**Describe the bug**
When Batman™: Arkham Knight starts, Python raises a UnicodeDecodeError error, which would prevent the fix to be applied. This happens even there is no fix file available. Something seems to be wrong with Protonfixes and this game (there might more games). When I remove Protonfixes from the config file, no error appears.

**To Reproduce**
- Install protonfixes
- run Batman™: Arkham Knight

**Expected behavior**
There shouldn't be an error and the protonfix, if available, should be applied.

**Logs**
https://gist.github.com/NoXPhasma/70eea75d4d6326a255a242de14f51d69

**Operating System:**
 - Distro and Version: Linux Mint 19
 - Proton Version: Proton 3.16-4 Beta

**Game (if applicable):**
 - Game Name: Batman™: Arkham Knight
 - Game ID: 208650

**Additional Information**
Add any other information [i.e. Modified Proton, Non-default Steam Library folder, etc] that might be useful in troubleshooting.

**Comment by simons-public** [comment]
Ok, I pushed a fix that handles the UnicodeDecodeError exception so that games will work for now. Is there any way you could upload your `appmanifest_208650.acf` file so I can figure out why the parsing failed?

**Comment by NoXPhasma** [comment]
Of course: https://gist.github.com/NoXPhasma/0d4e6efbb7ef58b47941b8c92a0d9789
