### ISSUE TITLE
Age of Empires II does not need fixes anymore

### ISSUE THREAD

**Issue by sehnem** [simons-public/protonfixes#61]
The proton 3.16 release corrected the error with the DLL that was not letting Age of Empires II (221380) start.

**Operating System:**
 - Distro and Version: Arch Linux
 - Proton Version: 3.16

**Game (if applicable):**
 - Game Name: Age of Empires II 
 - Game ID: 221380

**Comment by basxto** [comment]
The launcher fails on the first start and uses 2 windows, which looks a bit weird.

**Comment by simons-public** [comment]
Sorry to take so long, this should have been a quick fix
