### ISSUE TITLE
[Feature Request] Return Proton version

### ISSUE THREAD

**Issue by NoXPhasma** [simons-public/protonfixes#63]
Now with Proton 3.16-5 we have [FAudio](https://github.com/ValveSoftware/Proton/wiki/Changelog#316-5) support, which fixes most `xact` problems. Means that those fixes wouldn't be needed in most cases if a Version of 3.16-5 or higher is been used. And we will most probably hit much more upstream fixes in the future.

Now it would be nice to have a function to give back the version in use. However, best would be to give it back as list, like `[3, 16, 5]`. In that case it would be easy to check for that.

**Comment by pchome** [comment]
The only version you can get locally -- is the "timestamp" from the `version` file in Proton's directory.
`$ date -d "@$(cat version)"`

Which, btw, also easy to check:
```python
# 2018/12/10, 3.16-5
if util.proton_version() < 1544476838
    util.protontricks('xact')
```

**Comment by NoXPhasma** [comment]
This sounds like a way to go.
