### ISSUE TITLE
Hat in time crashed because of this

### ISSUE THREAD

**Issue by vjr2** [simons-public/protonfixes#72]
**Is your feature request related to a problem? Please describe.**
Yep, before hat in time ran out of the box, and now with protonfixes it won't run

**Describe the solution you'd like**
Disable protonfixes for this game. Is there a way to do it?

**Comment by simons-public** [comment]
I'll work on getting a blacklist for disabling protonfixes for specific games. In the meantime, can you post a debug log? I'd like to see if I can figure out why it's crashing as well, thanks.

**Comment by Jan200101** [comment]
runs fine for me using Protonfixes

**Comment by simons-public** [comment]
@Jan200101:
Thanks for the update, closing this issue.

@vjr2:
Also added a section on the wiki on how to [blacklist gamefixes for games](https://github.com/simons-public/protonfixes/wiki/Blacklist)
