### ISSUE TITLE
Have a check if user is on Big Picture Mode

### ISSUE THREAD

**Issue by MrCraigen** [simons-public/protonfixes#75]
**Is your feature request related to a problem? Please describe.**
Not a problem with protonfixes itself, but problem with companies that uses launchers in their games. Take a example, Batman Arkham Asylum here you need to use keyboard / mouse in order to move forward and launch the game. Hence breaks the Console Experience with SteamBox.

**Describe the solution you'd like**
Have a check in gamefix-script when user uses Big Picture Mode and use "util.replace_command" to skip launcher.

Like
`if util.protonbigpicture('SteamTenfoot')
        # Skip the launcher if using BPM for more Console Experience
        util.replace_command('Binaries/BmLauncher.exe', 'Binaries/BmStartApp.exe')`

**Comment by simons-public** [comment]
You could add this to a gamefix script by importing the `os` module. For example:

```
import os

...

# skip launcher if in big picture mode
if 'SteamTenfoot' in os.environ:
    util.replace_command('Binaries/BmLauncher.exe', 'Binaries/BmStartApp.exe')
```

**Comment by MrCraigen** [comment]
That simple? Awesome! Then we don't need to have this ticket open.
Thanks for the tips!
