### ISSUE TITLE
Implement protonfixes option to install "Media Foundation" dlls

### ISSUE THREAD

**Issue by GloriousEggroll** [simons-public/protonfixes#83]
**Is your feature request related to a problem? Please describe.**
A lot of games require the "Media Foundation" dlls to run properly, otherwise they render black screens or dont render movies or some other parts of the game properly A small sample of games affected by this are:
    Monster Hunter World
    Blaz Blue Central Fiction
    GRIS
    Breathedge
    FINAL FANTASY TYPE-0 HD
    Car Mechanic Simulator 2018
    PC Building Simulator
    American Fugitive
    Dauntless
    Remnant: From the Ashes

**Describe the solution you'd like**
The most popular workaround is to use the solution provided by this repo:

https://github.com/z0z0z/mf-install

It would be really useful to be able to have the repo as part of the project, and to execute the install script on the prefix based on a 'protonfixes' option that can be specified.

**Describe alternatives you've considered**
I may be able to code this myself and submit a PR, but my time is limited between my job and side projects. If you or someone is able to get to it before me it would be awesome and helpful.

**Comment by pchome** [comment]
> It would be really useful to be able to have the repo as part of the project, and to execute the install script on the prefix based on a 'protonfixes' option that can be specified.

Use custom winetricks verb, this already supported by the project.

See  `protonfixes/gamefixes/verbs/`.
Then just add e.g. `util.protontricks('mf-install')` to the gamefix file.

Refs: #43, https://github.com/Winetricks/winetricks/issues/1132, https://github.com/austin987/winetricks/commit/5d653bfd9f2282a1d77edd3e4ed71205be1c4894

**Comment by GloriousEggroll** [comment]
> > It would be really useful to be able to have the repo as part of the project, and to execute the install script on the prefix based on a 'protonfixes' option that can be specified.
> 
> Use custom winetricks verb, this already supported by the project.
> 
> See `protonfixes/gamefixes/verbs/`.
> Then just add e.g. `util.protontricks('mf-install')` to the gamefix file.
> 
> Refs: #43, [Winetricks/winetricks#1132](https://github.com/Winetricks/winetricks/issues/1132), [austin987/winetricks@5d653bf](https://github.com/austin987/winetricks/commit/5d653bfd9f2282a1d77edd3e4ed71205be1c4894)

thanks, was not aware this was added. I know they had 'mf' before but did not know they updated it. 

will close this issue.
