### ISSUE TITLE
Do setting os.environ from gamefix actually work?

### ISSUE THREAD

**Issue by pchome** [simons-public/protonfixes#9]
Previously was discussed a bit starting here: https://github.com/simons-public/protonfixes/issues/1#issuecomment-427629557 and further.
> To get sure I tried with os.environ["DXVK_HUD"] = "fps", but no FPS counter shows up.
> So, this won't work, because Proton overwrites these variables in the proton file.

I'm not familiar with Python, and maybe there is some magic when `os.environ` changed, but:
* Proton overrides many env vars and collects them in `env[]`
* Proton using `env=env` to path changed environment values
* protonfixes manipulating `os.environ` values which wouldn't be used (Proton already using `env[]`)

**To Reproduce**
`os.environ['DISPLAY'] = ':1'` or any  non-used display number

**Expected behavior**
With incorrect DISPLAY number wine should produce error:
```
0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

**Logs**
See above.

**Operating System:**
 - Distro and Version: not applicable
 - Proton Version: Proton 3.7 Beta

**Game (if applicable):**
 - Game Name: any
 - Game ID: any

**Additional Information**
* Changing `os.environ` from gamefix can be applied for some variables, where Proton using `env['something'] = os.environ['something']` w/o further `env[]` modification. But mostly have no effect on other env vars.

* Thus won't  working changes to `os.environ`:
https://github.com/simons-public/protonfixes/commit/a715b01f43526d385e86bd8ea20693fc48d28ee8#diff-c2124c09416fd6d5f490aa2b9c34fb65
https://github.com/simons-public/protonfixes/commit/cf11887cd63eea601a2a497e733a937a3516b246#diff-9ca019334d39053ddb8f59e215595cec

* I'm using modified Proton version to respect some env vars, e.g. https://github.com/ValveSoftware/Proton/pull/1705

* I'm using modified protonfixes version to change env vars, e.g. https://gist.github.com/pchome/da43ab29de689cc3c21445e2c7fb0676

**Comment by simons-public** [comment]
You're right, I checked /proc/PID/environ in a game launched and the env vars from os.environ didn't get passed. I added a util.set_environment that actually sets the environment (tested with DXVK_HUD by checking in /proc/PID/environ for the exe process).

**Comment by simons-public** [comment]
Please let me know if this works in your environment and I'll close the issue

**Comment by pchome** [comment]
I should try to rewrite my gamefixes using new features and drop my local hacks first.
Closing for now, I'll reopen the issue if there are still problems present.

**Comment by pchome** [comment]
Yep, everything is ok.

With #12 changes I can drop my `user_settings` hacks and convert my previous gamefix to:
```python
import os
from protonfixes import util
from protonfixes.logger import log

def main():
    """ GTA IV: EFLC game
    """
    log.info('Applying fixes for GTA IV: EFLC')
    util.append_argument('-nomemrestrict')
    util.append_argument('-norestrictions')
    util.append_argument('-fullspecaudio')
    util.append_argument('-notimefix')
    util.disable_dxvk()
    util.set_environment('__GL_SHADER_DISK_CACHE_PATH', util.get_game_install_path())
    util.set_environment('LD_PRELOAD', 'libstrangle.so')
    util.set_environment('VSYNC', '0')
    util.set_environment('FPS', '240')
    util.set_environment('PICMIP', '-1')
```
